### ISSUE TITLE
Strings translation support

### ISSUE THREAD

**Issue by Gytjarek** [robmarshall/next-gravity-forms#14]
Since we usually work on projects that support multiple languages, I would like to create a plan for implementing internationalization. It would be ideal to store all strings in a `strings.js` file and devise a strategy for translating them. Perhaps we can achieve this by passing strings as prop to the form and adjusting the code accordingly. @robmarshall maybe you have a better idea? 

I would like to work on it as soon as possible as it is quite importnat feature for us

**Comment by robmarshall** [comment]
_Perhaps we can achieve this by passing strings as prop to the form and adjusting the code accordingly._

I think this may be the best thing to do at the moment. I already have concerns that helper messages are unable to be edited. 
For example, if I wanted "This is an invalid phone number" to be "Oops - check your digits" - this is currently not possible.

What are your thoughts on:

If there was a "helpersText" object that the user could overwrite all or some messages. Which would then be merged with the internal error string file.

e.g.
```
helperText: {
    required: 'Should be included',
   pattern: {
      email: 'This is wrong',
  }
}
```

Merged with our base strings:

```
errors: {
    general:
      "There was a problem with your submission. Errors have been highlighted below.",
    leastOneField: "At least one field must be filled out.",
    unknownError: "An unknown error occured.",
    required: "This field is required.",
    pattern: {
      email:
        "The email address entered is invalid, please check the formatting (e.g. email@domain.com).",
      phone: "This is an invalid phone number.",
      default: "The format seems to be wrong.",
    },
    maxChar: {
      front: "Need more than",
      back: "characters.",
    },
  }
  ```
  
  Would be:
  ```
errors: {
    general:
      "There was a problem with your submission. Errors have been highlighted below.",
    leastOneField: "At least one field must be filled out.",
    unknownError: "An unknown error occured.",
    required: 'Should be included',
    pattern: {
      email: "This is wrong",
      phone: "This is an invalid phone number.",
      default: "The format seems to be wrong.",
    },
    maxChar: {
      front: "Need more than",
      back: "characters.",
    },
  }
```

Then users can handle their own translations by passing in different strings depending on the what is needed.

We could provide a documented example of how to do this, but would rather not include translations within the package,

**Comment by Gytjarek** [comment]
this can be close within this pr: https://github.com/robmarshall/next-gravity-forms/pull/18
