### ISSUE TITLE
It is possible to submit form without completing the CAPTCHA

### ISSUE THREAD

**Issue by bohdangoeshike** [robmarshall/next-gravity-forms#24]
The user is able to submit a form without ticking "I am not a robot" on CAPTCHA. This occurs without any error message or indication that the CAPTCHA is a required field.

**Comment by robmarshall** [comment]
@bohdangoeshike Thanks for the heads up.

**Comment by robmarshall** [comment]
Fixed in: https://github.com/robmarshall/next-gravity-forms/pull/29
