### ISSUE TITLE
Expose "setField" from React Hook Forms to allow dynamic injection

### ISSUE THREAD

**Issue by Abdullah-J01** [robmarshall/next-gravity-forms#27]
I am submitting a form from frontend (next js) but I noticed all fields are not submitting.
I checked the graphQL request that is generated in the network tab upon submitting, it doesn't show all the fields
The fields that were not available there have some important things to consider.
They are "hidden"
Their value is assigned via javascript
But before submission, i checked the value using chrome dev tools and the field had value
But those fields are important and this package is not sending them with form data due to some reason. Please help

**Comment by robmarshall** [comment]
@Abdullah-J01 can you expand on this a little more. I was able to submit a form just now no problem.

Can you provide an example of the issue, so we can replicate and look into.

**Comment by Abdullah-J01** [comment]
@robmarshall Hey! Thank you for responding. Actually i further  investigated the issue. The problem is that, if i use Javascript to get an element by ID and change it's  value, it shows the new value in the markup. But upon form submission, it submits the initial / original value. 
In my case, as the field is hidden, it doesn't  has an initial/default  value. So it just ignores it. Also I tried setting a default value, then even after changing value using JS, it still submits the default / initial one. This is where I am stuck 

Thank you

**Comment by robmarshall** [comment]
Have you tried using the "presetValues" prop?

### Passing in Preset Values

Sometimes you will want to conditionally set default values, or pass in data to hidden fields. This could be values for a user ID, or a current page.

This is handled by the `presetValues` prop.

```js
<GravityFormForm data={form} presetValues={{ input_2: "My preset value" }} />
```

In the above example `input_2` corresponds to the 2nd field added in the WordPress Gravity Forms edit page. This value can be found by clicking on the field and looking at the top right just under Field Settings.

**Comment by Abdullah-J01** [comment]
> Have you tried using the "presetValues" prop?
> 
> ### Passing in Preset Values
> Sometimes you will want to conditionally set default values, or pass in data to hidden fields. This could be values for a user ID, or a current page.
> 
> This is handled by the `presetValues` prop.
> 
> ```js
> <GravityFormForm data={form} presetValues={{ input_2: "My preset value" }} />
> ```
> 
> In the above example `input_2` corresponds to the 2nd field added in the WordPress Gravity Forms edit page. This value can be found by clicking on the field and looking at the top right just under Field Settings.

@robmarshall  - Yes i did try this. Let me explain my issue in a bit more detail.

I am using "trustedForm" Api
For that script to work, I need my form to be in the DOM. So i render the form.
Then I have some values generated by TrustedForm that I have to insert in fields of that form. But the problem is, the form is already rendered, so using `**presetValues**` is no longer useful. That's why i used plain JS to change the value 

but when i submit form, it submits to the value i set in presetValues or the default value (if any)

**Comment by robmarshall** [comment]
@Abdullah-J01 That make sense. It sounds like next-gravity-forms may need to expose the "setfields" function from React Hook Forms.

That is unlikely to happen in the short term. A solution for right now may be to run your API first, and then render this package - once you have the details you need to inject.

**Comment by Abdullah-J01** [comment]
@robmarshall  - Yeah that would be a great addition. 
Also, another thing is the `Page break`. Support for that would be great as well

**Comment by Abdullah-J01** [comment]
Hey @robmarshall  - All of a sudden my form is not submitting anymore
It is not creating the graphql request it was making previously (in the network tab of chrome dev tools).
Can you verify this at your end please
