### ISSUE TITLE
Gravity Forms Data Incomplete: Missing submitButton Property Causes Errors in next-gravity-forms

### ISSUE THREAD

**Issue by Socipedia** [robmarshall/next-gravity-forms#60]
I am using the next-gravity-forms plugin to integrate Gravity Forms into my Next.js application. However, I am encountering an error where the form data is incomplete, specifically missing the submitButton property. This causes the application to throw the following error:

```
Form data is incomplete or missing submitButton: undefined 
    at GravityForm (webpack-internal:///./src/components/GravityForm.js:8:11)
    at div
    at div
    at div
```

I have verified that the form ID is correct and the form exists in Gravity Forms. I have also logged the fetched form data to the console and confirmed that the submitButton property is missing.

Any guidance on how to ensure the submitButton property is included in the fetched form data would be greatly appreciated. Thank you!

**Comment by Gytjarek** [comment]
Hey @Socipedia! It would be helpful if you could provide as many details as possible. Which version of the package or plugin are you using? Do you use the GraphQL plugin or the REST API? where does this error come from?

**Comment by Socipedia** [comment]
Thank you for your response @Gytjarek. Here are the details of my setup and the error I am encountering:

Package/Plugin Versions:
WPGraphQL: 1.27.2
WPGraphQL for Gravity Forms: 0.13.0
next-gravity-forms: 2.1.0

GraphQL or REST API:
I am using the GraphQL plugin.

```
"use client";

import GravityFormForm from "next-gravity-forms";

const GravityForm = ({ form }) => {
    console.log('GravityForm data:', form);

    if (!form || !form.submitButton) {
        console.warn('Form data is incomplete or missing submitButton:', form);
        return <div>Form data is incomplete or missing submitButton</div>;
    }

    return <GravityFormForm data={form} />;
};

export default GravityForm;
```
log:
`Form data is incomplete or missing submitButton: undefined`

I have confirmed that the submitButton field is present in the GraphQL query response:

```
{
  gfForms {
    nodes {
      id
      title
      databaseId
      submitButton {
        imageUrl
        layoutGridColumnSpan
        location
        text
        type
        width
      }
    }
  }
}
```

**Comment by Gytjarek** [comment]
@Socipedia try to log `form` object and debug it. The data you get from query looks like the following: 

> "data": {
    "gfForm": {
      "submitButton": {
        "text": "Submit1"
      }
    }
  },
  
So,`submitButton` prop is part of an inner property `gfForm`, and it is not located directly in the data object

**Comment by Gytjarek** [comment]
@Socipedia do you get the right data by `getGravityForm ` function.  What do you get in your logs? can you provide form object?

**Comment by Socipedia** [comment]
@Gytjarek Currently, the issue has shifted to a confirmation error. Below is the log data:

```
⨯ TypeError: Cannot read properties of undefined (reading 'confirmations')
    at eval (webpack-internal:///./node_modules/next-gravity-forms/cjs/index-Q4P2mYww.cjs.js:8981:486)
```

**Comment by Gytjarek** [comment]
@Socipedia most likely, you are not getting the correct data from your form. We destruct `confirmations` from the `data.gfForm` object. If it is `undefined` or something you get the error. This should be handled in the package, and we'll fix it, but I suggest debugging the data you get using the `getGravityForm` function

**Comment by Socipedia** [comment]
@Gytjarek thx for your respond

```
Form data: {
  gfForm: {
    databaseId: 1,
    description: 'Contact Us For Detail',
    descriptionPlacement: 'BELOW',
    labelPlacement: 'TOP',
    subLabelPlacement: 'BELOW',
    title: 'Contact Us',
    submitButton: {
      conditionalLogic: null,
      imageUrl: null,
      text: 'HIRE ME!',
      type: 'TEXT'
    },
    confirmations: [ [Object] ],
    hasHoneypot: true,
    formFields: { nodes: [Array] },
    pagination: null
  },
  gfSettings: {
  }
}
```

previously the error occurred due to my PropTypes for confirmation issue.
then another error appeared to replace it. Is there anything I did wrong in implementing it?

error log:
```
 ⨯ TypeError: Cannot read properties of undefined (reading 'replace')
    at On (webpack-internal:///./node_modules/next-gravity-forms/cjs/index-Q4P2mYww.cjs.js:3095:44)
    at Pn (webpack-internal:///./node_modules/next-gravity-forms/cjs/index-Q4P2mYww.cjs.js:3216:69)

   9 |   return (
  10 |     <div
> 11 |       id={`gfield_description_${wrapId.replace(/^field_/, "")}`}
     |                                        ^
  12 |       className={classNames("gfield_description", className)}
  13 |       dangerouslySetInnerHTML={{ __html: description }}
  14 |     />
```

**Comment by Gytjarek** [comment]
@Socipedia good catch, most likely, the issue occurs due to the description in the captcha field. As an option, you could temporarily remove the description from the captcha field or create a PR to fix it in the package itself. Otherwise, you should wait until it gets fixed

**Comment by Socipedia** [comment]
@Gytjarek I've fixed this, but another issue reappears, namely every time I submit what always appears is:
      "There was a problem with your submission. Please review the fields below.",

There is no problem on the client side, the server side too. looks like it's a reCAPTCHA issue again, I'm using v2 invisible

**Comment by Gytjarek** [comment]
@Socipedia I'll look into this today

**Comment by Gytjarek** [comment]
@Socipedia I've tried to set up your form, and it works for me without any errors, including the captcha field. I see you also use a honeypot field. Make sure you don't add a value for that fake field; otherwise, you will get errors.

**Comment by Socipedia** [comment]
@Gytjarek thanks for the help, now it works
