### ISSUE TITLE
Required conditional fields prevent form submission

### ISSUE THREAD

**Issue by cluke009** [robmarshall/next-gravity-forms#69]
As the title states if you have a conditionally required field you can not submit the form.

Running the latest version of this module 2.1.2 and all supporting modules are fairly up to date.

Gravity Forms export: [gravityforms-export-2024-08-07 (1).json](https://github.com/user-attachments/files/16531971/gravityforms-export-2024-08-07.1.json)

**Comment by cluke009** [comment]
Built the latest git version and the conditional logic looks to be working. Thanks for the quick fix on this.

**Comment by Gytjarek** [comment]
We've released version 2.1.3, which should resolve this issue. Therefore, I'm closing it now
