### ISSUE TITLE
Label for HTML block

### ISSUE THREAD

**Issue by cluke009** [robmarshall/next-gravity-forms#73]
If the label for an HTML block in Gravity Forms is set it will display on the frontend. The default label is "HTML Block" which is displayed above the content. If I remove this label from the Gravity Form the label is still displayed but rendered as null on the frontend. 

As I understand based on the field label help text  "Enter the label for this HTML block. It will help you identify your HTML blocks in the form editor, but it will not be displayed on the form."  I don't believe displaying this text is the intended behavior. 

I don't have a patch to submit but removing labelFor={labelFor} from the InputWrapper in /src/components/Html/index.js will resolve this.

**Comment by cvanh** [comment]
Good Afternoon, thanks for reporting. It should be resolved now can you check?
