### ISSUE TITLE
next-gravity-forms Date Picker Type Error

### ISSUE THREAD

**Issue by codeninja0415** [robmarshall/next-gravity-forms#74]
Hi
Now I am trying to use Gravity-forms in the Nextjs (14.24) but when I select the date-picker I got below error.
Please help me :)
![image](https://github.com/user-attachments/assets/9fe59796-4016-4f67-8ea0-101e49dc91dc)

**Comment by cvanh** [comment]
Hi, This issue has been resolved in V2.1.3 could you check?
