### ISSUE TITLE
MaxLength Issue - Conditional

### ISSUE THREAD

**Issue by robmarshall** [robmarshall/next-gravity-forms#9]
https://github.com/robmarshall/next-gravity-forms/pull/6 - Highlighted by @Gytjarek

It seems like there's an issue with themaxLength functionality. It works fine when a GF field has a maximum length set in a form. However, when it's not defined, it always returns an error. As a fix, a conditional check should be added:

`<input   maxLength: maxLength > 0 && { value: maxLength, message:   ...messageHere />`

**Comment by sheikahamed123** [comment]
what is the start command for the application

**Comment by robmarshall** [comment]
@sheikahamed123 I need to add some dev start up instructions to the readme. And hot reload. Until then:

I  use the following repo to test frontend: https://github.com/robmarshall/next-gravity-forms-example

**How to test on the above repo**

- Clone the next-gravity-forms package to your local
- Clone https://github.com/robmarshall/next-gravity-forms-example to your local
- Remove the next-gravity-forms package from the above repos `package.json`
- Install packages on example repo
- Navigate into your local "next-gravity-forms" root.
- Install packages
- Build it using "yarn build"
- Navigate into the `/dist` folder and run yarn link
- Navigate back to the example repo root and run yarn link "next-gravity-forms"

 _Every time you make a change, you need to run `yarn build`._

Now you can work on the package, whilst seeing it in a "live" environment.

**Comment by sheikahamed123** [comment]
Thanks I'll contribute no worries
